#!/usr/bin/env python
# -*- mode: python -*-
import sys
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('action')
parser.add_argument('package')
args = parser.parse_args()

if args.action not in ('install', 'upgrade'):
   sys.exit('invalid action')

if args.package.startswith('-'):
   sys.exit('invalid package name')

os.execvp('gravelpkg', ['gravelpkg', args.action, args.package])
